### ISSUE TITLE
Unnecessary content 

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipxproject.github.io#1]
I just looked at the source tree. Why is anything other than pipx/index.html present?

**Comment by itsayellow** [comment]
This is only a bounce for a specific page, not a whole site 301 redirect.  This is because Github Pages don't give us access to anything like an `.htaccess` file.

So I believe this means we have to redirect every web page individually.

**Comment by cs01** [comment]
I just clicked through some folders and found it's just a bunch of redirects. I assumed it was all the mkdocs content for the actual docs. I get it now, my bad.
