### ISSUE TITLE
Add root level index.html

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipxproject.github.io#2]
I saw someone mention they often accidentally go to the root GitHub page rather than the /pipx url. 

We should add an index.html redirect file to handle that case as well. Right now it’s a 404.

**Comment by itsayellow** [comment]
Ok will do.  BTW even the 404 page shows a link to the pypa/pipx site, so at least it's still informative.

**Comment by itsayellow** [comment]
I added a redirect from https://pipxproject.github.io -> https://pypa.github.io/pipx
