### ISSUE TITLE
Should we delay before redirecting

### ISSUE THREAD

**Issue by itsayellow** [pipxproject/pipxproject.github.io#3]
Right now all the pages wait 0 seconds before redirecting to the corresponding pypa pages.

Is there a value to waiting a couple of seconds so that users can see they are being redirected and need to update their links?

**Comment by cs01** [comment]
I am fine with just leaving it at 0 seconds. The url in the address bar updates after the redirect, so if anyone wants to share from here forward they'll get the right address. Plus this repo is hosted by GitHub so it doesn't take any extra effort to have it remain hosted and served indefinitely.

**Comment by itsayellow** [comment]
Cool, thanks for your thoughts!
